services:
    dtc_grid.renderer.factory:
        public: true
        class: Dtc\GridBundle\Grid\Renderer\RendererFactory
        arguments:
            - "@router"
            - "@translator"
            - "@service_container"
    dtc_grid.command.source_list:
        public: true
        class: Dtc\GridBundle\Command\SourceListCommand
        calls:
            - [ "setGridSourceManager", ['@dtc_grid.manager.source'] ]
        tags:
            - { name: console.command }
    dtc_grid.command.generate_grid_source:
        public: true
        class: Dtc\GridBundle\Command\GenerateGridSourceCommand
        calls:
            - [ "setRegistry", ['@?doctrine'] ]
            - [ "setMongoDBRegistry", ['@?doctrine_mongodb'] ]
            - [ "setEntityManager", ['@?doctrine.orm.default_entity_manager'] ]
            - [ "setDocumentManager", ['@?doctrine_mongodb.odm.default_document_manager'] ]
        tags:
            - { name: console.command }
    dtc_grid.column.source:
        public: true
        class: Dtc\GridBundle\Grid\Source\ColumnSource
        arguments:
            - "%kernel.cache_dir%"
            - "%kernel.debug%"
    dtc_grid.manager.source:
        public: true
        class: Dtc\GridBundle\Manager\GridSourceManager
        arguments:
            - "@dtc_grid.column.source"
        calls:
            - [ 'setReader', ['@?annotation_reader']]
            - [ 'setReflectionAllowedEntities', ['%dtc_grid.reflection.allowed_entities%']]
    dtc_grid.twig.extension:
        class: Dtc\GridBundle\Twig\Extension\TwigExtension
        tags:
            - { name: twig.extension }
    dtc_grid.command.source.list:
        class: Dtc\GridBundle\Command\SourceListCommand
        tags:
            - { name: 'console.command' }
    dtc_grid.command.source.generate:
        class: Dtc\GridBundle\Command\GenerateGridSourceCommand
        tags:
            - { name: 'console.command' }
    dtc_grid.controller.grid:
        public: true
        class: Dtc\GridBundle\Controller\GridController
        arguments:
            - "@service_container"
